In [1]:
import numpy as np
import pandas as pd

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([[2,3],[4,5]])
c=np.array([[2,3,5],[8,4,2],[3,5,6]])
d=np.array([[5,4,3,5],[3,6,3,4],[3,4,6,4],[2,4,6,7]])
e=np.array([[2,3,4,5,6],[4,6,7,3,5],[2,5,7,8,7],[3,5,6,3,5],[3,5,7,2,1]])
print(a)
print(b)
print(c)
print(d)
print(e)

[1 2 3 4 5]
[[2 3]
 [4 5]]
[[2 3 5]
 [8 4 2]
 [3 5 6]]
[[5 4 3 5]
 [3 6 3 4]
 [3 4 6 4]
 [2 4 6 7]]
[[2 3 4 5 6]
 [4 6 7 3 5]
 [2 5 7 8 7]
 [3 5 6 3 5]
 [3 5 7 2 1]]


In [4]:
from numpy import linalg as la

In [5]:
g=la.det(b)
h=la.det(c)
i=la.det(d)
j=la.det(e)

In [6]:
g

-2.0

In [7]:
h

41.999999999999986

In [8]:
i

246.00000000000014

In [9]:
j

31.999999999999986

In [10]:
la.inv(b)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [11]:
la.inv(c)

array([[ 0.33333333,  0.16666667, -0.33333333],
       [-1.        , -0.07142857,  0.85714286],
       [ 0.66666667, -0.02380952, -0.38095238]])

In [12]:
la.inv(d)

array([[ 0.29268293, -0.14634146,  0.12195122, -0.19512195],
       [-0.15853659,  0.32926829, -0.02439024, -0.06097561],
       [-0.10569106, -0.11382114,  0.31707317, -0.04065041],
       [ 0.09756098, -0.04878049, -0.29268293,  0.26829268]])

In [13]:
la.inv(e)

array([[ 9.37500000e-01,  9.37500000e-01, -4.37500000e-01,
        -1.50000000e+00,  2.50000000e-01],
       [-1.84375000e+00,  2.15625000e+00,  1.09375000e+00,
        -1.25000000e+00, -1.12500000e+00],
       [ 9.06250000e-01, -2.09375000e+00, -6.56250000e-01,
         1.75000000e+00,  8.75000000e-01],
       [-9.37500000e-02,  9.06250000e-01,  3.43750000e-01,
        -1.25000000e+00, -1.25000000e-01],
       [ 2.50000000e-01, -7.50000000e-01, -2.50000000e-01,
         1.00000000e+00, -6.34413157e-17]])

In [14]:
la.matrix_rank(a)

1

In [15]:
la.matrix_rank(b)

2

In [16]:
la.matrix_rank(c)

3

In [17]:
la.matrix_rank(d)

4

In [18]:
la.matrix_rank(e)

5

In [19]:
np.diag(a)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [20]:
np.diag(b)

array([2, 5])

In [21]:
np.diag(c)

array([2, 4, 6])

In [22]:
np.diag(d)

array([5, 6, 6, 7])

In [23]:
np.diag(e)

array([2, 6, 7, 3, 1])

In [24]:
np.trace(b)

7

In [25]:
np.trace(c)

12

In [26]:
np.trace(d)

24

In [27]:
np.trace(e)

19

In [28]:
x,y=la.eig(b) #eigenvalues and eigenvectors
print("roots:",x)
print("vectors:",y)

roots: [-0.27491722  7.27491722]
vectors: [[-0.79681209 -0.49436913]
 [ 0.60422718 -0.86925207]]


In [29]:
x,y=la.eig(c)   #eigenvalues and eigenvectors
print("roots:",x)
print("vectors:",y)

roots: [12.65719688+0.j         -0.32859844+1.79172914j -0.32859844-1.79172914j]
vectors: [[ 0.47320009+0.j          0.32595578-0.23326695j  0.32595578+0.23326695j]
 [ 0.58868615+0.j         -0.78988042+0.j         -0.78988042-0.j        ]
 [ 0.65538561+0.j          0.40571447+0.2254419j   0.40571447-0.2254419j ]]


In [30]:
x,y=la.eig(d)  #eigenvalues and eigenvectors
print("roots:",x)
print("vectors:",y)

roots: [17.32219788+0.j          2.25347414+1.20984236j  2.25347414-1.20984236j
  2.17085385+0.j        ]
vectors: [[-0.49300529+0.j         -0.25929797-0.47829445j -0.25929797+0.47829445j
   0.54311082+0.j        ]
 [-0.45668614+0.j         -0.37134806+0.0565252j  -0.37134806-0.0565252j
  -0.79147874+0.j        ]
 [-0.48857274+0.j         -0.20034153+0.25794587j -0.20034153-0.25794587j
   0.1630921 +0.j        ]
 [-0.5564892 +0.j          0.67544926+0.j          0.67544926-0.j
   0.22801976+0.j        ]]


In [31]:
x,y=la.eig(e)  #eigenvalues and eigenvectors
print("roots:",x)
print("vectors:",y)

roots: [23.4928956 +0.j         -3.98371416+0.j          0.32954074+0.42904225j
  0.32954074-0.42904225j -1.16826292+0.j        ]
vectors: [[ 0.37294205+0.j         -0.49507162+0.j         -0.05141235-0.40194495j
  -0.05141235+0.40194495j  0.29894562+0.j        ]
 [ 0.48571021+0.j          0.11302542+0.j         -0.67860975+0.j
  -0.67860975-0.j          0.3412559 +0.j        ]
 [ 0.55520831+0.j         -0.38953773+0.j          0.5348255 +0.19469741j
   0.5348255 -0.19469741j -0.36060803+0.j        ]
 [ 0.42552773+0.j         -0.08065914+0.j         -0.15501354-0.05279275j
  -0.15501354+0.05279275j  0.58058001+0.j        ]
 [ 0.36833367+0.j          0.7641229 +0.j          0.15498809+0.02242478j
   0.15498809-0.02242478j -0.57189565+0.j        ]]


In [2]:
data=pd.read_csv(r"C:\Users\SCET\Downloads\4_Drug200.csv")

In [3]:
data

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [4]:
data1=data.drop(['Sex','BP','Cholesterol','Drug'],axis=1)
data1

Age  Na_to_K
0     23   25.355
1     47   13.093
2     47   10.114
3     28    7.798
4     61   18.043
..   ...      ...
195   56   11.567
196   16   12.006
197   52    9.894
198   23   14.020
199   40   11.349

[200 rows x 2 columns]

In [5]:
data1.mean()

Age        44.315000
Na_to_K    16.084485
dtype: float64

In [6]:
data1.mode()

Age  Na_to_K
0  47.0   12.006
1   NaN   18.295

In [7]:
data1.median()

Age        45.0000
Na_to_K    13.9365
dtype: float64

In [8]:
data1.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [9]:
data1.sum()

Age        8863.000
Na_to_K    3216.897
dtype: float64

In [10]:
data1.cumsum()

Age   Na_to_K
0      23    25.355
1      70    38.448
2     117    48.562
3     145    56.360
4     206    74.403
..    ...       ...
195  8732  3169.628
196  8748  3181.634
197  8800  3191.528
198  8823  3205.548
199  8863  3216.897

[200 rows x 2 columns]

In [11]:
data.count()

Age            200
Sex            200
BP             200
Cholesterol    200
Na_to_K        200
Drug           200
dtype: int64

In [12]:
data1.min()

Age        15.000
Na_to_K     6.269
dtype: float64

In [13]:
data1.max()

Age        74.000
Na_to_K    38.247
dtype: float64

In [14]:
from numpy import cov
covarience=cov(data["Age"],data["Na_to_K"])
print(covarience)

[[273.71434673  -7.54375153]
 [ -7.54375153  52.18553348]]


In [15]:
from scipy.stats import pearsonr
corr,_=pearsonr(data["Age"],data["Na_to_K"])
corr


-0.0631194972677259

In [16]:
from scipy.stats import spearmanr
corr,_=spearmanr(data["Age"],data["Na_to_K"])
corr


-0.047273882688479915

In [18]:
from numpy import cov
covarience=cov(data["Age"],data["Na_to_K"])
print(covarience)

[[273.71434673  -7.54375153]
 [ -7.54375153  52.18553348]]


In [19]:
data2= pd.read_csv(r"C:\Users\SCET\Downloads\3_Fitness.csv")
data2

SALESMAN    JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES  \
0             ANU   70.0   80.0   75.0   60.0   72.0   55.0        412.0   
1            BABU   30.0   48.0   35.0   45.0   25.0   37.0        220.0   
2         CHANDRU   65.0   54.0   49.0   54.0   35.0   65.0        322.0   
3           DAVID   85.0   71.0   68.0   77.0   88.0   73.0        462.0   
4        EINSTEIN   55.0   25.0   45.0   50.0   53.0   30.0        258.0   
5          FAROOK   35.0   45.0   15.0   45.0   45.0   25.0        210.0   
6         GOWTHAM   75.0   66.0   59.0   65.0   56.0   30.0        351.0   
7        HARSHITH   29.0   35.0   49.0   48.0   35.0   55.0        247.0   
8          INIYAN   35.0   35.0   50.0   59.0   67.0   73.0        319.0   
9            JOHN   77.0   85.0   77.0   68.0   56.0   25.0        388.0   
10  MONTHLY SALES  556.0  544.0  522.0  571.0  532.0  468.0          NaN   
11            NaN    NaN    NaN    NaN    NaN    NaN    NaN       3189.0   

    Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0          NaN         NaN          NaN   
1          NaN         NaN          NaN   
2          NaN         NaN          NaN   
3          NaN         NaN          NaN   
4          NaN         NaN          NaN   
5          NaN         NaN          NaN   
6          NaN         NaN          NaN   
7          NaN         NaN          NaN   
8          NaN         NaN          NaN   
9          NaN         NaN          NaN   
10      3193.0         NaN          NaN   
11         NaN         NaN          NaN   

                                          Unnamed: 11  
0                                                 NaN  
1                     1. Individual Sales using Sum()  
2   2. Find the pattern trend using conditional fo...  
3   3. Analyze using Pivot table as column percentage  
4                              4. Insert Pivot charts  
5   5. Rank() - returns the rank of a given value ...  
6                                                 NaN  
7                                                  33  
8                                                 NaN  
9                                                 NaN  
10                                                NaN  
11                                                NaN

In [20]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   SALESMAN     11 non-null     object 
 1   JAN          11 non-null     float64
 2   FEB          11 non-null     float64
 3   MAR          11 non-null     float64
 4   APR          11 non-null     float64
 5   MAY          11 non-null     float64
 6   JUN          11 non-null     float64
 7   TOTAL SALES  11 non-null     float64
 8   Unnamed: 8   1 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  6 non-null      object 
dtypes: float64(10), object(2)
memory usage: 1.3+ KB


In [21]:
data2.describe()

JAN         FEB         MAR         APR         MAY         JUN  \
count   11.000000   11.000000   11.000000   11.000000   11.000000   11.000000   
mean   101.090909   98.909091   94.909091  103.818182   96.727273   85.090909   
std    152.263886  148.884153  142.770763  155.277054  145.500578  128.347540   
min     29.000000   25.000000   15.000000   45.000000   25.000000   25.000000   
25%     35.000000   40.000000   47.000000   49.000000   40.000000   30.000000   
50%     65.000000   54.000000   50.000000   59.000000   56.000000   55.000000   
75%     76.000000   75.500000   71.500000   66.500000   69.500000   69.000000   
max    556.000000  544.000000  522.000000  571.000000  532.000000  468.000000   

       TOTAL SALES  Unnamed: 8  Unnamed: 9  Unnamed: 10  
count    11.000000         1.0         0.0          0.0  
mean    579.818182      3193.0         NaN          NaN  
std     869.142775         NaN         NaN          NaN  
min     210.000000      3193.0         NaN          NaN  
25%     252.500000      3193.0         NaN          NaN  
50%     322.000000      3193.0         NaN          NaN  
75%     400.000000      3193.0         NaN          NaN  
max    3189.000000      3193.0         NaN          NaN

In [22]:
data2=data2.drop(['SALESMAN','Unnamed: 8','Unnamed: 9','Unnamed: 10','Unnamed: 11'],axis=1)
data2

JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES
0    70.0   80.0   75.0   60.0   72.0   55.0        412.0
1    30.0   48.0   35.0   45.0   25.0   37.0        220.0
2    65.0   54.0   49.0   54.0   35.0   65.0        322.0
3    85.0   71.0   68.0   77.0   88.0   73.0        462.0
4    55.0   25.0   45.0   50.0   53.0   30.0        258.0
5    35.0   45.0   15.0   45.0   45.0   25.0        210.0
6    75.0   66.0   59.0   65.0   56.0   30.0        351.0
7    29.0   35.0   49.0   48.0   35.0   55.0        247.0
8    35.0   35.0   50.0   59.0   67.0   73.0        319.0
9    77.0   85.0   77.0   68.0   56.0   25.0        388.0
10  556.0  544.0  522.0  571.0  532.0  468.0          NaN
11    NaN    NaN    NaN    NaN    NaN    NaN       3189.0

In [24]:
data2=data2.fillna(data2.median())
data2

JAN    FEB    MAR    APR    MAY    JUN  TOTAL SALES
0    70.0   80.0   75.0   60.0   72.0   55.0        412.0
1    30.0   48.0   35.0   45.0   25.0   37.0        220.0
2    65.0   54.0   49.0   54.0   35.0   65.0        322.0
3    85.0   71.0   68.0   77.0   88.0   73.0        462.0
4    55.0   25.0   45.0   50.0   53.0   30.0        258.0
5    35.0   45.0   15.0   45.0   45.0   25.0        210.0
6    75.0   66.0   59.0   65.0   56.0   30.0        351.0
7    29.0   35.0   49.0   48.0   35.0   55.0        247.0
8    35.0   35.0   50.0   59.0   67.0   73.0        319.0
9    77.0   85.0   77.0   68.0   56.0   25.0        388.0
10  556.0  544.0  522.0  571.0  532.0  468.0        322.0
11   65.0   54.0   50.0   59.0   56.0   55.0       3189.0

In [26]:
print(data2.median())
print(data2.mode())
print(data2.mean())

JAN             65.0
FEB             54.0
MAR             50.0
APR             59.0
MAY             56.0
JUN             55.0
TOTAL SALES    322.0
dtype: float64
    JAN   FEB   MAR   APR   MAY   JUN  TOTAL SALES
0  35.0  35.0  49.0  45.0  56.0  55.0        322.0
1  65.0  54.0  50.0  59.0   NaN   NaN          NaN
JAN             98.083333
FEB             95.166667
MAR             91.166667
APR            100.083333
MAY             93.333333
JUN             82.583333
TOTAL SALES    558.333333
dtype: float64


In [27]:
print(data2.count())
print(data2.cumsum())
print(data2.sum())
print(data2.min())
print(data2.max())

JAN            12
FEB            12
MAR            12
APR            12
MAY            12
JUN            12
TOTAL SALES    12
dtype: int64
       JAN     FEB     MAR     APR     MAY    JUN  TOTAL SALES
0     70.0    80.0    75.0    60.0    72.0   55.0        412.0
1    100.0   128.0   110.0   105.0    97.0   92.0        632.0
2    165.0   182.0   159.0   159.0   132.0  157.0        954.0
3    250.0   253.0   227.0   236.0   220.0  230.0       1416.0
4    305.0   278.0   272.0   286.0   273.0  260.0       1674.0
5    340.0   323.0   287.0   331.0   318.0  285.0       1884.0
6    415.0   389.0   346.0   396.0   374.0  315.0       2235.0
7    444.0   424.0   395.0   444.0   409.0  370.0       2482.0
8    479.0   459.0   445.0   503.0   476.0  443.0       2801.0
9    556.0   544.0   522.0   571.0   532.0  468.0       3189.0
10  1112.0  1088.0  1044.0  1142.0  1064.0  936.0       3511.0
11  1177.0  1142.0  1094.0  1201.0  1120.0  991.0       6700.0
JAN            1177.0
FEB            1142.

In [28]:
from scipy.stats import spearmanr 
corr,_=spearmanr(data2["JAN"],data2["TOTAL SALES"])
print(corr)

0.7188060310021683


In [29]:
from scipy.stats import pearsonr
corr,_=pearsonr(data2["JAN"],data2["TOTAL SALES"])
print(corr)

-0.059402675873807015


In [30]:
from numpy import cov
covarience=cov(data2["JAN"],data2["TOTAL SALES"])
print(covarience)

[[ 21185.17424242  -7193.84848485]
 [ -7193.84848485 692274.78787879]]


In [31]:
data3= pd.read_csv(r"C:\Users\SCET\Downloads\1_2015.csv")
data3

Country                           Region  Happiness Rank  \
0    Switzerland                   Western Europe               1   
1        Iceland                   Western Europe               2   
2        Denmark                   Western Europe               3   
3         Norway                   Western Europe               4   
4         Canada                    North America               5   
..           ...                              ...             ...   
153       Rwanda               Sub-Saharan Africa             154   
154        Benin               Sub-Saharan Africa             155   
155        Syria  Middle East and Northern Africa             156   
156      Burundi               Sub-Saharan Africa             157   
157         Togo               Sub-Saharan Africa             158   

     Happiness Score  Standard Error  Economy (GDP per Capita)   Family  \
0              7.587         0.03411                   1.39651  1.34951   
1              7.561         0.04884                   1.30232  1.40223   
2              7.527         0.03328                   1.32548  1.36058   
3              7.522         0.03880                   1.45900  1.33095   
4              7.427         0.03553                   1.32629  1.32261   
..               ...             ...                       ...      ...   
153            3.465         0.03464                   0.22208  0.77370   
154            3.340         0.03656                   0.28665  0.35386   
155            3.006         0.05015                   0.66320  0.47489   
156            2.905         0.08658                   0.01530  0.41587   
157            2.839         0.06727                   0.20868  0.13995   

     Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                     0.94143  0.66557                        0.41978   
1                     0.94784  0.62877                        0.14145   
2                     0.87464  0.64938                        0.48357   
3                     0.88521  0.66973                        0.36503   
4                     0.90563  0.63297                        0.32957   
..                        ...      ...                            ...   
153                   0.42864  0.59201                        0.55191   
154                   0.31910  0.48450                        0.08010   
155                   0.72193  0.15684                        0.18906   
156                   0.22396  0.11850                        0.10062   
157                   0.28443  0.36453                        0.10731   

     Generosity  Dystopia Residual  
0       0.29678            2.51738  
1       0.43630            2.70201  
2       0.34139            2.49204  
3       0.34699            2.46531  
4       0.45811            2.45176  
..          ...                ...  
153     0.22628            0.67042  
154     0.18260            1.63328  
155     0.47179            0.32858  
156     0.19727            1.83302  
157     0.16681            1.56726  

[158 rows x 12 columns]

In [32]:
data3.describe()

Happiness Rank  Happiness Score  Standard Error  \
count      158.000000       158.000000      158.000000   
mean        79.493671         5.375734        0.047885   
std         45.754363         1.145010        0.017146   
min          1.000000         2.839000        0.018480   
25%         40.250000         4.526000        0.037268   
50%         79.500000         5.232500        0.043940   
75%        118.750000         6.243750        0.052300   
max        158.000000         7.587000        0.136930   

       Economy (GDP per Capita)      Family  Health (Life Expectancy)  \
count                158.000000  158.000000                158.000000   
mean                   0.846137    0.991046                  0.630259   
std                    0.403121    0.272369                  0.247078   
min                    0.000000    0.000000                  0.000000   
25%                    0.545808    0.856823                  0.439185   
50%                    0.910245    1.029510                  0.696705   
75%                    1.158448    1.214405                  0.811013   
max                    1.690420    1.402230                  1.025250   

          Freedom  Trust (Government Corruption)  Generosity  \
count  158.000000                     158.000000  158.000000   
mean     0.428615                       0.143422    0.237296   
std      0.150693                       0.120034    0.126685   
min      0.000000                       0.000000    0.000000   
25%      0.328330                       0.061675    0.150553   
50%      0.435515                       0.107220    0.216130   
75%      0.549092                       0.180255    0.309883   
max      0.669730                       0.551910    0.795880   

       Dystopia Residual  
count         158.000000  
mean            2.098977  
std             0.553550  
min             0.328580  
25%             1.759410  
50%             2.095415  
75%             2.462415  
max             3.602140

In [33]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Country                        158 non-null    object 
 1   Region                         158 non-null    object 
 2   Happiness Rank                 158 non-null    int64  
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 1

In [34]:
data3=data3.drop(['Country','Region'],axis=1)
data3

Happiness Rank  Happiness Score  Standard Error  \
0                 1            7.587         0.03411   
1                 2            7.561         0.04884   
2                 3            7.527         0.03328   
3                 4            7.522         0.03880   
4                 5            7.427         0.03553   
..              ...              ...             ...   
153             154            3.465         0.03464   
154             155            3.340         0.03656   
155             156            3.006         0.05015   
156             157            2.905         0.08658   
157             158            2.839         0.06727   

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     1.39651  1.34951                   0.94143  0.66557   
1                     1.30232  1.40223                   0.94784  0.62877   
2                     1.32548  1.36058                   0.87464  0.64938   
3                     1.45900  1.33095                   0.88521  0.66973   
4                     1.32629  1.32261                   0.90563  0.63297   
..                        ...      ...                       ...      ...   
153                   0.22208  0.77370                   0.42864  0.59201   
154                   0.28665  0.35386                   0.31910  0.48450   
155                   0.66320  0.47489                   0.72193  0.15684   
156                   0.01530  0.41587                   0.22396  0.11850   
157                   0.20868  0.13995                   0.28443  0.36453   

     Trust (Government Corruption)  Generosity  Dystopia Residual  
0                          0.41978     0.29678            2.51738  
1                          0.14145     0.43630            2.70201  
2                          0.48357     0.34139            2.49204  
3                          0.36503     0.34699            2.46531  
4                          0.32957     0.45811            2.45176  
..                             ...         ...                ...  
153                        0.55191     0.22628            0.67042  
154                        0.08010     0.18260            1.63328  
155                        0.18906     0.47179            0.32858  
156                        0.10062     0.19727            1.83302  
157                        0.10731     0.16681            1.56726  

[158 rows x 10 columns]

In [36]:
data3=data3.fillna(data3.median())
data3

Happiness Rank  Happiness Score  Standard Error  \
0                 1            7.587         0.03411   
1                 2            7.561         0.04884   
2                 3            7.527         0.03328   
3                 4            7.522         0.03880   
4                 5            7.427         0.03553   
..              ...              ...             ...   
153             154            3.465         0.03464   
154             155            3.340         0.03656   
155             156            3.006         0.05015   
156             157            2.905         0.08658   
157             158            2.839         0.06727   

     Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                     1.39651  1.34951                   0.94143  0.66557   
1                     1.30232  1.40223                   0.94784  0.62877   
2                     1.32548  1.36058                   0.87464  0.64938   
3                     1.45900  1.33095                   0.88521  0.66973   
4                     1.32629  1.32261                   0.90563  0.63297   
..                        ...      ...                       ...      ...   
153                   0.22208  0.77370                   0.42864  0.59201   
154                   0.28665  0.35386                   0.31910  0.48450   
155                   0.66320  0.47489                   0.72193  0.15684   
156                   0.01530  0.41587                   0.22396  0.11850   
157                   0.20868  0.13995                   0.28443  0.36453   

     Trust (Government Corruption)  Generosity  Dystopia Residual  
0                          0.41978     0.29678            2.51738  
1                          0.14145     0.43630            2.70201  
2                          0.48357     0.34139            2.49204  
3                          0.36503     0.34699            2.46531  
4                          0.32957     0.45811            2.45176  
..                             ...         ...                ...  
153                        0.55191     0.22628            0.67042  
154                        0.08010     0.18260            1.63328  
155                        0.18906     0.47179            0.32858  
156                        0.10062     0.19727            1.83302  
157                        0.10731     0.16681            1.56726  

[158 rows x 10 columns]

In [38]:
print(data3.median())
print(data3.mode())
print(data3.mean())

Happiness Rank                   79.500000
Happiness Score                   5.232500
Standard Error                    0.043940
Economy (GDP per Capita)          0.910245
Family                            1.029510
Health (Life Expectancy)          0.696705
Freedom                           0.435515
Trust (Government Corruption)     0.107220
Generosity                        0.216130
Dystopia Residual                 2.095415
dtype: float64
     Happiness Rank  Happiness Score  Standard Error  \
0              82.0            5.192         0.03751   
1               NaN              NaN         0.03780   
2               NaN              NaN         0.04394   
3               NaN              NaN         0.04934   
4               NaN              NaN         0.05051   
..              ...              ...             ...   
153             NaN              NaN             NaN   
154             NaN              NaN             NaN   
155             NaN              NaN             Na

In [40]:
print(data3.count())
print(data3.cumsum())
print(data3.sum())
print(data3.min())
print(data3.max())

Happiness Rank                   158
Happiness Score                  158
Standard Error                   158
Economy (GDP per Capita)         158
Family                           158
Health (Life Expectancy)         158
Freedom                          158
Trust (Government Corruption)    158
Generosity                       158
Dystopia Residual                158
dtype: int64
     Happiness Rank  Happiness Score  Standard Error  \
0                 1            7.587         0.03411   
1                 3           15.148         0.08295   
2                 6           22.675         0.11623   
3                10           30.197         0.15503   
4                15           37.624         0.19056   
..              ...              ...             ...   
153           11934          837.276         7.32523   
154           12089          840.616         7.36179   
155           12245          843.622         7.41194   
156           12402          846.527         7.49852   
1

In [43]:
from scipy.stats import pearsonr
corr,_=pearsonr(data3["Freedom"],data3["Generosity"])
print(corr)

0.3739161255744058


In [45]:
from scipy.stats import spearmanr
corr,_=spearmanr(data3["Freedom"],data3["Generosity"])
print(corr)

0.4184577985545189


In [46]:
from numpy import cov
covarience=cov(data3["Freedom"],data3["Generosity"])
print(covarience)

[[0.02270832 0.00713825]
 [0.00713825 0.01604907]]


In [47]:
data4= pd.read_csv(r"C:\Users\SCET\Downloads\7_Uber.csv")
data4

Unnamed: 0                            key  fare_amount  \
0         24238194    2015-05-07 19:52:06.0000003          7.5   
1         27835199    2009-07-17 20:04:56.0000002          7.7   
2         44984355   2009-08-24 21:45:00.00000061         12.9   
3         25894730    2009-06-26 08:22:21.0000001          5.3   
4         17610152  2014-08-28 17:47:00.000000188         16.0   
...            ...                            ...          ...   
199995    42598914   2012-10-28 10:49:00.00000053          3.0   
199996    16382965    2014-03-14 01:09:00.0000008          7.5   
199997    27804658   2009-06-29 00:42:00.00000078         30.9   
199998    20259894    2015-05-20 14:56:25.0000004         14.5   
199999    11951496   2010-05-15 04:08:00.00000076         14.1   

                pickup_datetime  pickup_longitude  pickup_latitude  \
0       2015-05-07 19:52:06 UTC        -73.999817        40.738354   
1       2009-07-17 20:04:56 UTC        -73.994355        40.728225   
2       2009-08-24 21:45:00 UTC        -74.005043        40.740770   
3       2009-06-26 08:22:21 UTC        -73.976124        40.790844   
4       2014-08-28 17:47:00 UTC        -73.925023        40.744085   
...                         ...               ...              ...   
199995  2012-10-28 10:49:00 UTC        -73.987042        40.739367   
199996  2014-03-14 01:09:00 UTC        -73.984722        40.736837   
199997  2009-06-29 00:42:00 UTC        -73.986017        40.756487   
199998  2015-05-20 14:56:25 UTC        -73.997124        40.725452   
199999  2010-05-15 04:08:00 UTC        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[200000 rows x 9 columns]

In [48]:
data4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   Unnamed: 0         200000 non-null  int64  
 1   key                200000 non-null  object 
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  object 
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64  
dtypes: float64(5), int64(2), object(2)
memory usage: 13.7+ MB


In [49]:
data4.describe()

Unnamed: 0    fare_amount  pickup_longitude  pickup_latitude  \
count  2.000000e+05  200000.000000     200000.000000    200000.000000   
mean   2.771250e+07      11.359955        -72.527638        39.935885   
std    1.601382e+07       9.901776         11.437787         7.720539   
min    1.000000e+00     -52.000000      -1340.648410       -74.015515   
25%    1.382535e+07       6.000000        -73.992065        40.734796   
50%    2.774550e+07       8.500000        -73.981823        40.752592   
75%    4.155530e+07      12.500000        -73.967154        40.767158   
max    5.542357e+07     499.000000         57.418457      1644.421482   

       dropoff_longitude  dropoff_latitude  passenger_count  
count      199999.000000     199999.000000    200000.000000  
mean          -72.525292         39.923890         1.684535  
std            13.117408          6.794829         1.385997  
min         -3356.666300       -881.985513         0.000000  
25%           -73.991407         40.733823         1.000000  
50%           -73.980093         40.753042         1.000000  
75%           -73.963658         40.768001         2.000000  
max          1153.572603        872.697628       208.000000

In [50]:
data4=data4.drop(['key','pickup_datetime'],axis=1)
data4

Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
0         24238194          7.5        -73.999817        40.738354   
1         27835199          7.7        -73.994355        40.728225   
2         44984355         12.9        -74.005043        40.740770   
3         25894730          5.3        -73.976124        40.790844   
4         17610152         16.0        -73.925023        40.744085   
...            ...          ...               ...              ...   
199995    42598914          3.0        -73.987042        40.739367   
199996    16382965          7.5        -73.984722        40.736837   
199997    27804658         30.9        -73.986017        40.756487   
199998    20259894         14.5        -73.997124        40.725452   
199999    11951496         14.1        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[200000 rows x 7 columns]

In [52]:
data4=data4.fillna(data4.mode())
data4

Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
0         24238194          7.5        -73.999817        40.738354   
1         27835199          7.7        -73.994355        40.728225   
2         44984355         12.9        -74.005043        40.740770   
3         25894730          5.3        -73.976124        40.790844   
4         17610152         16.0        -73.925023        40.744085   
...            ...          ...               ...              ...   
199995    42598914          3.0        -73.987042        40.739367   
199996    16382965          7.5        -73.984722        40.736837   
199997    27804658         30.9        -73.986017        40.756487   
199998    20259894         14.5        -73.997124        40.725452   
199999    11951496         14.1        -73.984395        40.720077   

        dropoff_longitude  dropoff_latitude  passenger_count  
0              -73.999512         40.723217                1  
1              -73.994710         40.750325                1  
2              -73.962565         40.772647                1  
3              -73.965316         40.803349                3  
4              -73.973082         40.761247                5  
...                   ...               ...              ...  
199995         -73.986525         40.740297                1  
199996         -74.006672         40.739620                1  
199997         -73.858957         40.692588                2  
199998         -73.983215         40.695415                1  
199999         -73.985508         40.768793                1  

[200000 rows x 7 columns]

In [54]:
print(data4.median())
print(data4.mode())
print(data4.mean())

Unnamed: 0           2.774550e+07
fare_amount          8.500000e+00
pickup_longitude    -7.398182e+01
pickup_latitude      4.075259e+01
dropoff_longitude   -7.398009e+01
dropoff_latitude     4.075304e+01
passenger_count      1.000000e+00
dtype: float64
        Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
0                1          6.5               0.0              0.0   
1               45          NaN               NaN              NaN   
2               48          NaN               NaN              NaN   
3              243          NaN               NaN              NaN   
4              335          NaN               NaN              NaN   
...            ...          ...               ...              ...   
199995    55421687          NaN               NaN              NaN   
199996    55421949          NaN               NaN              NaN   
199997    55422851          NaN               NaN              NaN   
199998    55422902          NaN               N

In [55]:
print(data4.count())
print(data4.cumsum())
print(data4.sum())
print(data4.min())
print(data4.max())

Unnamed: 0           200000
fare_amount          200000
pickup_longitude     200000
pickup_latitude      200000
dropoff_longitude    199999
dropoff_latitude     199999
passenger_count      200000
dtype: int64
           Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
0            24238194         7.50     -7.399982e+01     4.073835e+01   
1            52073393        15.20     -1.479942e+02     8.146658e+01   
2            97057748        28.10     -2.219992e+02     1.222073e+02   
3           122952478        33.40     -2.959753e+02     1.629982e+02   
4           140562630        49.40     -3.699004e+02     2.037423e+02   
...               ...          ...               ...              ...   
199995  5542424337457   2271924.05     -1.450523e+07     7.987014e+06   
199996  5542440720422   2271931.55     -1.450531e+07     7.987055e+06   
199997  5542468525080   2271962.45     -1.450538e+07     7.987096e+06   
199998  5542488784974   2271976.95     -1.450545e+07     7.98

In [57]:
from scipy.stats import pearsonr
corr,_=pearsonr(data4["fare_amount"],data4["passenger_count"])
print(corr)

0.01014992555452919


In [58]:
from scipy.stats import spearmanr
corr,_=spearmanr(data4["fare_amount"],data4["passenger_count"])
print(corr)

0.023295665466744574


In [59]:
from numpy import cov
covarience=cov(data4["fare_amount"],data4["passenger_count"])
print(covarience)

[[98.04517241  0.13929583]
 [ 0.13929583  1.92098644]]


In [77]:
data5= pd.read_csv(r"C:\Users\SCET\Downloads\9_Bottle.csv")
data5

C:\Users\SCET\AppData\Local\Temp\ipykernel_8932\1889592619.py:1: DtypeWarning: Columns (47,73) have mixed types. Specify dtype option on import or set low_memory=False.
  data5= pd.read_csv(r"C:\Users\SCET\Downloads\9_Bottle.csv")


Cst_Cnt  Btl_Cnt       Sta_ID                                Depth_ID  \
0             1        1  054.0 056.0  19-4903CR-HY-060-0930-05400560-0000A-3   
1             1        2  054.0 056.0  19-4903CR-HY-060-0930-05400560-0008A-3   
2             1        3  054.0 056.0  19-4903CR-HY-060-0930-05400560-0010A-7   
3             1        4  054.0 056.0  19-4903CR-HY-060-0930-05400560-0019A-3   
4             1        5  054.0 056.0  19-4903CR-HY-060-0930-05400560-0020A-7   
...         ...      ...          ...                                     ...   
864858    34404   864859  093.4 026.4  20-1611SR-MX-310-2239-09340264-0000A-7   
864859    34404   864860  093.4 026.4  20-1611SR-MX-310-2239-09340264-0002A-3   
864860    34404   864861  093.4 026.4  20-1611SR-MX-310-2239-09340264-0005A-3   
864861    34404   864862  093.4 026.4  20-1611SR-MX-310-2239-09340264-0010A-3   
864862    34404   864863  093.4 026.4  20-1611SR-MX-310-2239-09340264-0015A-3   

        Depthm  T_degC   Salnty  O2ml_L    STheta   O2Sat  ...  R_PHAEO  \
0            0  10.500  33.4400     NaN  25.64900     NaN  ...      NaN   
1            8  10.460  33.4400     NaN  25.65600     NaN  ...      NaN   
2           10  10.460  33.4370     NaN  25.65400     NaN  ...      NaN   
3           19  10.450  33.4200     NaN  25.64300     NaN  ...      NaN   
4           20  10.450  33.4210     NaN  25.64300     NaN  ...      NaN   
...        ...     ...      ...     ...       ...     ...  ...      ...   
864858       0  18.744  33.4083   5.805  23.87055  108.74  ...     0.18   
864859       2  18.744  33.4083   5.805  23.87072  108.74  ...     0.18   
864860       5  18.692  33.4150   5.796  23.88911  108.46  ...     0.18   
864861      10  18.161  33.4062   5.816  24.01426  107.74  ...     0.31   
864862      15  17.533  33.3880   5.774  24.15297  105.66  ...     0.61   

        R_PRES  R_SAMP  DIC1  DIC2  TA1  TA2  pH2  pH1  DIC Quality Comment  
0            0     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
1            8     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
2           10     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
3           19     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
4           20     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
...        ...     ...   ...   ...  ...  ...  ...  ...                  ...  
864858       0     NaN   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
864859       2     4.0   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
864860       5     3.0   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
864861      10     2.0   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  
864862      15     1.0   NaN   NaN  NaN  NaN  NaN  NaN                  NaN  

[864863 rows x 74 columns]

In [69]:
data5.describe()

Cst_Cnt        Btl_Cnt         Depthm         T_degC  \
count  864863.000000  864863.000000  864863.000000  853900.000000   
mean    17138.790958  432432.000000     226.831951      10.799677   
std     10240.949817  249664.587269     316.050259       4.243825   
min         1.000000       1.000000       0.000000       1.440000   
25%      8269.000000  216216.500000      46.000000       7.680000   
50%     16848.000000  432432.000000     125.000000      10.060000   
75%     26557.000000  648647.500000     300.000000      13.880000   
max     34404.000000  864863.000000    5351.000000      31.140000   

              Salnty         O2ml_L         STheta          O2Sat  \
count  817509.000000  696201.000000  812174.000000  661274.000000   
mean       33.840350       3.392468      25.819394      57.103779   
std         0.461843       2.073256       1.167787      37.094137   
min        28.431000      -0.010000      20.934000      -0.100000   
25%        33.488000       1.360000      24.965000      21.100000   
50%        33.863000       3.440000      25.996000      54.400000   
75%        34.196900       5.500000      26.646000      97.600000   
max        37.034000      11.130000     250.784000     214.100000   

         Oxy_µmol/Kg         BtlNum  ...         R_CHLA        R_PHAEO  \
count  661268.000000  118667.000000  ...  225276.000000  225275.000000   
mean      148.808694      10.497426  ...       0.450225       0.198599   
std        90.187533       6.189688  ...       1.208566       0.376539   
min        -0.434900       0.000000  ...      -0.010000      -3.890000   
25%        60.915470       5.000000  ...       0.050000       0.050000   
50%       151.064150      10.000000  ...       0.160000       0.110000   
75%       240.379600      16.000000  ...       0.390000       0.230000   
max       485.701800      25.000000  ...      66.110000      65.300000   

              R_PRES         R_SAMP         DIC1         DIC2          TA1  \
count  864863.000000  122006.000000  1999.000000   224.000000  2084.000000   
mean      228.395694     162.071521  2153.239714  2168.148330  2256.055845   
std       319.456731      85.722796   112.995202   154.852332    34.844435   
min         0.000000       0.000000  1948.850000  1969.440000  2181.570000   
25%        46.000000     200.000000  2028.330000  2008.977500  2230.322500   
50%       126.000000     206.000000  2170.640000  2265.885000  2244.325000   
75%       302.000000     214.000000  2253.810000  2315.525000  2278.505000   
max      5458.000000     424.000000  2367.800000  2364.420000  2434.900000   

               TA2        pH2        pH1  
count   234.000000  10.000000  84.000000  
mean   2278.858803   7.948570   7.910983  
std      58.496495   0.021216   0.077666  
min    2198.150000   7.923100   7.618300  
25%    2229.062500   7.931475   7.898675  
50%    2247.505000   7.946650   7.928850  
75%    2316.452500   7.963300   7.955100  
max    2437.000000   7.988300   8.047700  

[8 rows x 70 columns]

In [71]:
data5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864863 entries, 0 to 864862
Data columns (total 74 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   Cst_Cnt              864863 non-null  int64  
 1   Btl_Cnt              864863 non-null  int64  
 2   Sta_ID               864863 non-null  object 
 3   Depth_ID             864863 non-null  object 
 4   Depthm               864863 non-null  int64  
 5   T_degC               853900 non-null  float64
 6   Salnty               817509 non-null  float64
 7   O2ml_L               696201 non-null  float64
 8   STheta               812174 non-null  float64
 9   O2Sat                661274 non-null  float64
 10  Oxy_µmol/Kg          661268 non-null  float64
 11  BtlNum               118667 non-null  float64
 12  RecInd               864863 non-null  int64  
 13  T_prec               853900 non-null  float64
 14  T_qual               23127 non-null   float64
 15  S_prec           

In [72]:
data5.columns

Index(['Cst_Cnt', 'Btl_Cnt', 'Sta_ID', 'Depth_ID', 'Depthm', 'T_degC',
       'Salnty', 'O2ml_L', 'STheta', 'O2Sat', 'Oxy_µmol/Kg', 'BtlNum',
       'RecInd', 'T_prec', 'T_qual', 'S_prec', 'S_qual', 'P_qual', 'O_qual',
       'SThtaq', 'O2Satq', 'ChlorA', 'Chlqua', 'Phaeop', 'Phaqua', 'PO4uM',
       'PO4q', 'SiO3uM', 'SiO3qu', 'NO2uM', 'NO2q', 'NO3uM', 'NO3q', 'NH3uM',
       'NH3q', 'C14As1', 'C14A1p', 'C14A1q', 'C14As2', 'C14A2p', 'C14A2q',
       'DarkAs', 'DarkAp', 'DarkAq', 'MeanAs', 'MeanAp', 'MeanAq', 'IncTim',
       'LightP', 'R_Depth', 'R_TEMP', 'R_POTEMP', 'R_SALINITY', 'R_SIGMA',
       'R_SVA', 'R_DYNHT', 'R_O2', 'R_O2Sat', 'R_SIO3', 'R_PO4', 'R_NO3',
       'R_NO2', 'R_NH4', 'R_CHLA', 'R_PHAEO', 'R_PRES', 'R_SAMP', 'DIC1',
       'DIC2', 'TA1', 'TA2', 'pH2', 'pH1', 'DIC Quality Comment'],
      dtype='object')

In [78]:
data5=data5.drop(['Depth_ID','Sta_ID',
        'O2ml_L', 'STheta', 'O2Sat', 'Oxy_µmol/Kg', 'BtlNum',
       'RecInd', 'T_prec', 'T_qual', 'S_prec', 'S_qual', 'P_qual', 'O_qual',
       'SThtaq', 'O2Satq', 'ChlorA', 'Chlqua', 'Phaeop', 'Phaqua', 'PO4uM',
       'PO4q', 'SiO3uM', 'SiO3qu', 'NO2uM', 'NO2q', 'NO3uM', 'NO3q', 'NH3uM',
       'NH3q', 'C14As1', 'C14A1p', 'C14A1q', 'C14As2', 'C14A2p', 'C14A2q',
       'DarkAs', 'DarkAp', 'DarkAq', 'MeanAs', 'MeanAp', 'MeanAq', 'IncTim',
       'LightP', 'R_Depth', 'R_TEMP', 'R_POTEMP', 'R_SALINITY', 'R_SIGMA',
       'R_SVA', 'R_DYNHT', 'R_O2', 'R_O2Sat', 'R_SIO3', 'R_PO4', 'R_NO3',
       'R_NO2', 'R_NH4', 'R_CHLA', 'R_PHAEO', 'R_PRES', 'R_SAMP', 'DIC1',
       'DIC2', 'TA1', 'TA2', 'pH2', 'pH1', 'DIC Quality Comment'],axis=1)
data5

Cst_Cnt  Btl_Cnt  Depthm  T_degC   Salnty
0             1        1       0  10.500  33.4400
1             1        2       8  10.460  33.4400
2             1        3      10  10.460  33.4370
3             1        4      19  10.450  33.4200
4             1        5      20  10.450  33.4210
...         ...      ...     ...     ...      ...
864858    34404   864859       0  18.744  33.4083
864859    34404   864860       2  18.744  33.4083
864860    34404   864861       5  18.692  33.4150
864861    34404   864862      10  18.161  33.4062
864862    34404   864863      15  17.533  33.3880

[864863 rows x 5 columns]

In [79]:
print(data5.median())
print(data5.mode())
print(data5.mean())

Cst_Cnt     16848.000
Btl_Cnt    432432.000
Depthm        125.000
T_degC         10.060
Salnty         33.863
dtype: float64
        Cst_Cnt  Btl_Cnt  Depthm  T_degC  Salnty
0       14467.0        1    10.0     9.1   33.58
1           NaN        2     NaN     NaN     NaN
2           NaN        3     NaN     NaN     NaN
3           NaN        4     NaN     NaN     NaN
4           NaN        5     NaN     NaN     NaN
...         ...      ...     ...     ...     ...
864858      NaN   864859     NaN     NaN     NaN
864859      NaN   864860     NaN     NaN     NaN
864860      NaN   864861     NaN     NaN     NaN
864861      NaN   864862     NaN     NaN     NaN
864862      NaN   864863     NaN     NaN     NaN

[864863 rows x 5 columns]
Cst_Cnt     17138.790958
Btl_Cnt    432432.000000
Depthm        226.831951
T_degC         10.799677
Salnty         33.840350
dtype: float64


In [80]:
print(data5.count())
print(data5.cumsum())
print(data5.sum())
print(data5.min())
print(data5.max())

Cst_Cnt    864863
Btl_Cnt    864863
Depthm     864863
T_degC     853900
Salnty     817509
dtype: int64
            Cst_Cnt       Btl_Cnt     Depthm       T_degC        Salnty
0                 1             1          0       10.500  3.344000e+01
1                 2             3          8       20.960  6.688000e+01
2                 3             6         18       31.420  1.003170e+02
3                 4            10         37       41.870  1.337370e+02
4                 5            15         57       52.320  1.671580e+02
...             ...           ...        ...          ...           ...
864858  14822568548  373990977370  196178530  9221770.992  2.766466e+07
864859  14822602952  373991842230  196178532  9221789.736  2.766469e+07
864860  14822637356  373992707091  196178537  9221808.428  2.766472e+07
864861  14822671760  373993571953  196178547  9221826.589  2.766476e+07
864862  14822706164  373994436816  196178562  9221844.122  2.766479e+07

[864863 rows x 5 columns]
Cst_Cn

In [82]:
data5=data5.fillna(data5.median())
data5

Cst_Cnt  Btl_Cnt  Depthm  T_degC   Salnty
0             1        1       0  10.500  33.4400
1             1        2       8  10.460  33.4400
2             1        3      10  10.460  33.4370
3             1        4      19  10.450  33.4200
4             1        5      20  10.450  33.4210
...         ...      ...     ...     ...      ...
864858    34404   864859       0  18.744  33.4083
864859    34404   864860       2  18.744  33.4083
864860    34404   864861       5  18.692  33.4150
864861    34404   864862      10  18.161  33.4062
864862    34404   864863      15  17.533  33.3880

[864863 rows x 5 columns]

In [83]:
from scipy.stats import pearsonr
corr,_=pearsonr(data5["Depthm"],data5["Salnty"])
print(corr)

0.5441125338932323


In [84]:
from scipy.stats import spearmanr
corr,_=spearmanr(data5["Depthm"],data5["Salnty"])
print(corr)

0.7464472057024376


In [85]:
from numpy import cov
covarience=cov(data5["Depthm"],data5["Salnty"])
print(covarience)

[[9.98877660e+04 7.72219527e+01]
 [7.72219527e+01 2.01647015e-01]]
